package com.example.temp.manager.vo.takein;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class TakeinOrderItemVO {
	public TakeinOrderItemVO() {
		nno = "";
		subNo = "";
		orgStation = "";
		userId = "";
		hsCode = "";
		itemDetail = "";
		nativeItemDetail = "";
		unitCurrency = "";
		itemCnt = "";
		unitValue = "";
		brand = "";
		makeCntry = "";
		makeCom = "";
		itemDiv = "";
		wtUnit = "";
		qtyUnit = "";
		packageUnit = ""; 
		exchangeRate = "";
		chgCurrency = "";
		chgAmt = "";
		itemMeterial = "";
		takeInCode = "";
		cusItemCode = "";
		itemUrl = "";
		itemImgUrl = "";
		trkCom = "";
		trkNo = "";
		trkDate = "";
		userWta = "";
		userWtc = "";
		itemValue = "";
		whOutCnt = "";
		wUserId = "";
		wUserIp = "";
		wDate = "";
		totalValue ="";
		totalWeight ="";
		idx=0;
		rackCode="";
	}
	private String nno;
	private String subNo;
	private String orgStation;
	private String userId;
	private String hsCode;
	private String itemDetail;
	private String nativeItemDetail;
	private String unitCurrency;
	private String itemCnt;
	private String unitValue;
	private String brand;
	private String makeCntry;
	private String makeCom;
	private String itemDiv;
	private String wtUnit;
	private String qtyUnit;
	private String packageUnit;
	private String exchangeRate;
	private String chgCurrency;
	private String chgAmt;
	private String itemMeterial;
	private String takeInCode;
	private String cusItemCode;
	private String itemUrl;
	private String itemImgUrl;
	private String trkCom;
	private String trkNo;
	private String trkDate;
	private String itemValue;
	private String userWta;
	private String userWtc;
	private String whOutCnt;
	private String itemWta;
	private String itemWtc;
	private String wUserId;
	private String wUserIp;
	private String wDate;
	private String totalWeight;
	private String totalValue;
	private int idx;
	private String rackCode;
}
